### ISSUE TITLE
Horizontal Review: Internationalization self test

### ISSUE THREAD

**Issue by iherman** [w3c/did-core#104]
To initiate an Internationalization Review, a group is supposed to look at, first, [the short check list](https://w3c.github.io/i18n-drafts/techniques/shortchecklist) and, if relevant, consider the relevant part of the [long check list](https://www.w3.org/International/techniques/developing-specs.en).

The short checklist entries are below. I checked those items that, in my view, _are not relevant for DID and DID documents_ (therefore, as far as the check is concerned, we are o.k.)

- [x] ... contains any natural language text that will be read by a human (this includes error messages or other UI text, JSON strings, etc, etc),
- [x] ... allows content authors to produce typographically appealing text, either in its own right, or in association with graphics.
- [x] ... allows the user to point into text, creates text fragments, concatenates text, allows the user to select or step through text (using a cursor or other methods), etc
- [x] ... allows searching or matching of text, including syntax and identifiers
- [x] ... sorts text
- [x] ... captures user input
- [x] ... deals with time in any way that will be read by humans and/or crosses time zone boundaries
- [x] ... allows any character encoding other than UTF-8
- [x] ... defines markup
- [x] ... deals with names, addresses, time & date formats, etc
- [x] ... describes a format or data that is likely to need localisation
- [x] ... makes any reference to or relies on any cultural norms

If we are all o.k. with the conclusions, I will contact the I18N IG group with a reference to this self test. If not then, of course, we will have to come to conclusion.

**Comment by iherman** [comment]
I wanted to be sure with the first item, hence I did not check it upfront: I believe the answer to this question is 'no', ie, a DID document does not have and natural language text item. But I would prefer some reinforcement on that from the WG.

**Comment by msporny** [comment]
> I wanted to be sure with the first item, hence I did not check it upfront: I believe the answer to this question is 'no', ie, a DID document does not have and natural language text item. But I would prefer some reinforcement on that from the WG.

Same answer as here: https://github.com/w3c/did-core/issues/105#issuecomment-554772655

**Comment by iherman** [comment]
And same answer as here: https://github.com/w3c/did-core/issues/105#issuecomment-554912917 😁

**Comment by iherman** [comment]
The latest editorial round on the Core (after the F2F meeting of Amsterdam) means that we will have to check these self-tests again. Once that is done, we should connect the I18N people to start the official horizontal review.

**Comment by iherman** [comment]
Discussed on 2020-04-14: when the current §3 and §6 gets filled in (which means that the final structure of the document is in place), we can go out to get the horizontal review done.

**Comment by brentzundel** [comment]
Related: https://w3c.github.io/string-meta/

**Comment by iherman** [comment]
related #313 has been raised and has to be closed via a PR

**Comment by xfq** [comment]
The i18n WG has reviewed the spec. We're OK with the spec once https://github.com/w3c/did-core/pull/319 is merged.

**Comment by iherman** [comment]
For the record, #319 has been merged on 25.06.'20.

**Comment by iherman** [comment]
@brentzundel @burnburn this is just a ping to notify that the I18N review is now complete.

**Comment by iherman** [comment]
@burnburn, @brentzundel, Per #104 (comment) and #104 (comment) we are done with I18N. We will use this issue as a reference for our CR transition call; we can leave it open to make the transition easier, but we can also close it. As you prefer.

**Comment by brentzundel** [comment]
> @burnburn, @brentzundel, Per #104 (comment) and #104 (comment) we are done with I18N. We will use this issue as a reference for our CR transition call; we can leave it open to make the transition easier, but we can also close it. As you prefer.

If leaving it open makes our lives easier, we should do so.

**Comment by brentzundel** [comment]
Keeping this open until transition to CR.

**Comment by msporny** [comment]
This is done, we're keeping this open until we make the request to go to CR.

**Comment by brentzundel** [comment]
Horizontal review is complete, closing
