### ISSUE TITLE
Horizontal Review Tracking

### ISSUE THREAD

**Issue by brentzundel** [w3c/did-core#292]
- [How to get horizontal review](https://www.w3.org/wiki/DocumentReview#How_to_get_horizontal_review)
- [Labels for facilitating horizontal review](https://w3c.github.io/issue-metadata.html#horizontal-reviews)

- [x] Internationalization - Issue #104 
- [x] Accessibility - Issue #105 
- [x] TAG Review - Issue #119
- [x] PING Review - Issue #291
- [x] DID Explainer - Issue #94

**Comment by brentzundel** [comment]
Horizontal review is complete, closing
